### ISSUE TITLE
can you update your  filetrees?

### ISSUE THREAD

**Issue by yangdongchao** [Jungjee/DcaseNet#2]
i want to run your code in my Machine, if you can show me your filetrees, i can understand how to run your code.

**Comment by Jungjee** [comment]
After downloading all three datasets, put them under a single folder like below.
Then run https://github.com/Jungjee/DcaseNet/blob/master/launch_nvidia-gpu-cloud.sh with 
DB_dir=[folder_name].

Afterward, you will be able to run both train and evaluation scripts. 
Let me know if something goes wrong.

[folder_name]
|
|--- dcase2020task1
|--- dcase...
|--- dcase....
