### ISSUE TITLE
can you add a requirements.txt?

### ISSUE THREAD

**Issue by Danzip** [Jungjee/DcaseNet#6]
for people running locally?

**Comment by Jungjee** [comment]
Hi, I'll add a list of libraries

**Comment by Jungjee** [comment]
Some of these libraries may not be required..
-----

apex==0.1
librosa==0.6.3
matplotlib==3.1.1
numpy==1.17.2
nvidia-dali==0.14.0
nvidia-ml-py3==7.352.0
opencv-python==3.4.1.15
pandas==0.24.2
pillow-simd==5.3.0.post1
pillow==7.0.0
pip==20.0.2
pycuda==2019.1.2
pyyaml==5.1.2
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
sox==1.3.7
tensorboard==2.0.0
torch-summary==1.4.2
torch==1.4.0
torchaudio==0.4.0
torchtext==0.4.0
torchvision==0.5.0
tqdm==4.31.1

**Comment by Danzip** [comment]
thanks!
