### ISSUE TITLE
can you please add DcasenetV1 and V2 to the code?

### ISSUE THREAD

**Issue by Danzip** [Jungjee/DcaseNet#8]
I intend to use DCASENET on a special case of sound event detection I require a small network, can you please add the code and weights for DcasenetV1? I don't need V2.

**Comment by Jungjee** [comment]
I'm sorry to tell you that as of current, I don't have plans to manage and upload those architectures, since they are not commented and code refactoring is required before sharing.

**Comment by Danzip** [comment]
Thank you, I would try to adapt DcasenetV3 for my case
